sudo: required

language: bash

services:
  - docker

before_install:
    - docker build --build-arg VUID=`id -u` -t ronin/arch-kernel .
    - mkdir deploy
    - docker run -v $PWD/deploy:/deploy ronin/arch-kernel 

