sudo: required
language: bash
services:
- docker
before_install:
- docker build --build-arg VUID=`id -u` -t ronin/arch-kernel .
- pwd && ls
- mkdir deploy
- docker run -v $PWD/deploy:/deploy ronin/arch-kernel
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key:
    secure: uR9sHO/9htkHGmIfh8ak+XEOALZt7cxe6foSDN/IpiO8FzOOU2Z3OopCVmbYf9aERkhjv411h3UJOByRuXCERgqA4Wb8wpRVQueyBYeCAjLDvBShj/wfa/yvIKsgxFO3vuqv/Uc2NSbfYJhPD6bVwUnAxaT/0y+MgmCPeyqNrWK46Xr0k2jO5rS6qH5TOtiP2WwtOQZ8b5mEoumDzycss31+m4DI28R3jA9hHVaHgSRNABSp2PKrNOQoS4DgRUW3neJBbg1LmibK2VQxMhZOJvKQOUewwn+HvFpZ/bHIKP0oBEeukvP7tZwpy+Hi7zs/SoPARE/XrbKFpW2DSErqU/f+lsG5njeOVRUti4W8fPAQ4AQ0h6HgEH9yctcEYO40au1YP766QNiaNk5JK3QU13QGFhDELNFiXCHArTIcbag7d4VfWo2dXUHefPA7QdSfu8t+neuUb6WikukqnyGRgN2mocLnAyjF8EtV8kJXA2JMghYJv6so6b2/PHVzUQwJmta4kcrg1/0wfrc1ZoSkQAOw96lSqyiHbRD19dlw7mSMPtwJLx7Z/BD1YEv42u4xQ7UwFUc0oPiSv4CG4MPYIPSKGrmsFkUxVwwu22W6ng7co+AErkRZCw1FyLJeoooDOsFQIOXK/vx/eF20TB6jMhrHMN6J9QEJnxJjFFg/WO4=
  file: "deploy/*"
  on:
    repo: ronin13/arch-kernel
